### PR TITLE
Fix Issue#676: Adding Tags for Crops

### LINKED ISSUE #676: Add warnings for Toxicity in crops
I noticed in your list of crops you have some poisonous varieties listed (such as baneberry and hemlock) there should probably be an indicator of potential toxicity. You could have icons that act as a quick visual indicator maybe? Some plants may only be partially edible. (ex... roots are edible, while fruit and/or leaves are not)

### PR DESCRIPTION
**Pull request by TanSA05**
Implemented tagging of crops:

* Used the mongoid_taggable gem to tag crops in the DB
* Used the ngTagsInput AngularJS library to tag crops on the front-end
* Improved autocomplete in tags_controller so that only the tags matching the query are returned in the dropdown
* Display tags on the crops#show page
* Written tests for crops_controller and tags_controller

An issue is that the ngTagsInput AngularJS library requires Angular 1.3+ while we're using Angular 1.3.beta. While the tagging system works perfectly (adding, deleting, updating etc.) there are some JS errors on the console when deleting a tag. I'm not sure how to handle that. Perhaps a new ticket for the same would be better?

This PR fixes #676

### CODE REVIEW

**Comment by simonv3** [comment]
Hey @TanSA05, can you tackle the hound statements above? Thanks!

File: spec/controllers/api/api_tags_controller_spec.rb [hunk 1]
```diff
@@ -0,0 +1,27 @@
+require 'spec_helper'
```
Comment (TanSA05) [inline spec/controllers/api/api_tags_controller_spec.rb]: @simonv3 Can you explain this comment? Google and stackoverflow only told me about ways to disable this feature. I'm not sure how to fix this.

Comment (kuldeepaggarwal) [inline spec/controllers/api/api_tags_controller_spec.rb]: Ignore this warning.

**Comment by simonv3** [comment]
Hey @TanSA05! Yay, everything passed :). Can you tackle the hound statements? 

I'll have time to properly review and merge Sunday afternoon.

**Comment by TanSA05** [comment]
@simonv3 Swamped with an assignment deadline for Sunday midnight (your Sunday morning), but I should be able to attend to Hound warnings before your Sunday afternoon. 😄

File: app/views/crops/show.html.erb [hunk 2]
```diff
@@ -34,6 +34,10 @@
           </td>
         </tr>
         <tr>
+          <td><%= I18n.t('crops.tags') %></td>
+          <td><%= @crop.tags.gsub(',',', ')%></td>
```
Comment (TanSA05) [inline app/views/crops/show.html.erb]: Thanks for the tip, @kuldeepaggarwal!

**Comment by TanSA05** [comment]
@simonv3 I added most of the colors in the variables file, but there are a lot that I have used in the CSS. Do I need to add all? Also, is there a tool I can use to fix the remaining Hound warnings? Fixing them individually is taking a really long time :confused:

**Comment by simonv3** [comment]
@TanSA05 you can maybe to a find & replace on some of them?

If you're using colours that are outside the standard OpenFarm colors, can you match them to the closest color? Or use SCSS [darken and lighten](https://robots.thoughtbot.com/controlling-color-with-sass-color-functions#darken-amp-lighten) from a variable color? The variables are pretty important because it means we can tweak the colors or change the color scheme in the future and be sure all our colors are updated appropriately. 

I'll go through and figure out which ones you should tackle.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 3]
```diff
@@ -0,0 +1,400 @@
...
+      border-top-left-radius: 0;
+      border-bottom-left-radius: 0;
+    }
+
+    &:last-child .tags {
+      border-top-right-radius: 0;
+      border-bottom-right-radius: 0;
+    }
+
+    &:first-child .tags {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely tackle this one.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 4]
```diff
@@ -0,0 +1,400 @@
...
+        padding: 0;
+        border: none;
+        background: none;
+        cursor: pointer;
+        vertical-align: middle;
+        font: bold 16px Arial, sans-serif;
+        color: #585858;
+      }
+
+      .remove-button:active {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely tackle this one.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 5]
```diff
@@ -0,0 +1,400 @@
...
+
+      .remove-button {
+        margin: 0 0 0 5px;
+        padding: 0;
+        border: none;
+        background: none;
+        cursor: pointer;
+        vertical-align: middle;
+        font: bold 16px Arial, sans-serif;
+        color: #585858;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely tackle this one.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 6]
```diff
@@ -0,0 +1,400 @@
...
+      }
+
+      .remove-button:active {
+          color: $red;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely tackle this one.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 7]
```diff
@@ -0,0 +1,400 @@
...
+      border-top-left-radius: 0;
+      border-bottom-left-radius: 0;
+    }
+
+    &:last-child .tags {
+      border-top-right-radius: 0;
+      border-bottom-right-radius: 0;
+    }
+
+    &:first-child .tags {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely tackle this one.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 8]
```diff
@@ -0,0 +1,400 @@
...
+        padding: 0;
+        border: none;
+        background: none;
+        cursor: pointer;
+        vertical-align: middle;
+        font: bold 16px Arial, sans-serif;
+        color: #585858;
+
+        &:active {
+          color: #ff0000;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: We definitely have a red variable.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 9]
```diff
@@ -0,0 +1,400 @@
...
+  }
+}
+
+.keywords[disabled] {
+
+  .tags {
+    background-color: $lighter-gray;
+
+    .tag-item {
+      background: #337ab7;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: We do have some blues I think? But maybe this should be green?

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 10]
```diff
@@ -0,0 +1,400 @@
...
+      border-top-right-radius: 0;
+      border-bottom-right-radius: 0;
+    }
+
+    &:first-child .tags {
+      border-top-left-radius: 0;
+      border-bottom-left-radius: 0;
+    }
+
+    &:last-child .tags {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: All of these should be merged IMO

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 11]
```diff
@@ -0,0 +1,400 @@
...
+  }
+}
+
+.has-error .keywords .tags {
+  border-color: $deep-red;
+
+  &.focused {
+    border-color: $deeper-red;
+    -webkit-box-shadow: inset 0 1px 1px $background-color, 0 0 6px $light-red;
+    -moz-box-shadow: inset 0 1px 1px $background-color, 0 0 6px $light-red;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Ditto to the one below

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 12]
```diff
@@ -0,0 +1,400 @@
...
+  }
+}
+
+.has-warning .keywords .tags {
+  border-color: #8a6d3b;
+
+  &.focused {
+    border-color: $dark-yellow;
+    -webkit-box-shadow: inset 0 1px 1px $background-color, 0 0 6px $pale-orange;
+    -moz-box-shadow: inset 0 1px 1px $background-color, 0 0 6px $pale-orange;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Ditto to the ones below

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 13]
```diff
@@ -0,0 +1,399 @@
...
+  .tags {
+    background-color: #eeeeee;
+
+    .tag-item {
+      background: #337ab7;
+      opacity: 0.65;
+    }
+
+    .input {
+      background-color: #eeeeee;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: $light-gray

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 14]
```diff
@@ -0,0 +1,399 @@
...
+
+.input-group {
+
+  .keywords {
+    padding: 0;
+    display: table-cell;
+  }
+}
+
+.input-group .keywords:not(:first-child) .tags {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely do this one

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 15]
```diff
@@ -0,0 +1,399 @@
...
+  border-top-left-radius: 0;
+  border-bottom-left-radius: 0;
+}
+
+.input-group .keywords:not(:last-child) .tags {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Definitely do this one

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 16]
```diff
@@ -0,0 +1,399 @@
...
+  border-top-right-radius: 0px;
+  border-bottom-right-radius: 0px;
+}
+
+.has-feedback .keywords .tags {
+  padding-right: 30px;
+}
+
+.has-success .keywords .tags {
+  border-color: #cccccc;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: $dark-grey or lighten($dark-grey)

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 17]
```diff
@@ -0,0 +1,399 @@
...
+
+  &.focused {
+    border-color: #cccccc;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Ditto

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 18]
```diff
@@ -0,0 +1,399 @@
...
+    -webkit-box-shadow: inset 0 1px 1px $background-color, 0 0 6px #67b168;
+    -moz-box-shadow: inset 0 1px 1px $background-color, 0 0 6px #67b168;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: vendor prefixes fix I suggested below (drop prefix)

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 19]
```diff
@@ -0,0 +1,399 @@
...
+}
+
+.has-success .keywords .tags {
+  border-color: #cccccc;
+
+  &.focused {
+    border-color: #cccccc;
+    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
+    -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
+    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: You can also look at https://robots.thoughtbot.com/controlling-color-with-sass-color-functions#adding-alpha-transparency

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 20]
```diff
@@ -0,0 +1,399 @@
...
+  }
+}
+
+.has-error .keywords .tags {
+  border-color: #a94442;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: There's already a red.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 21]
```diff
@@ -0,0 +1,399 @@
...
+
+  &.focused {
+    border-color: #843534;
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: There's already a red

File: app/assets/javascripts/crops/edit.js [hunk 22]
```diff
@@ -30,6 +35,8 @@ openFarmApp.controller('cropCtrl', ['$scope', '$http', 'cropService',
         }
       }
 
+      var tags_array = $.map($scope.crop.tags_array, function(obj) { return obj.text; })
```
Comment (simonv3) [inline app/assets/javascripts/crops/edit.js]: Deffo fix this one

File: app/controllers/api/v1/tags_controller.rb [hunk 23]
```diff
@@ -0,0 +1,8 @@
+class Api::V1::TagsController < Api::V1::BaseController
```
Comment (simonv3) [inline app/controllers/api/v1/tags_controller.rb]: You can ignore this one because the rest of the app uses it, but I bet there is a better way.

File: app/controllers/api/v1/tags_controller.rb [hunk 24]
```diff
@@ -0,0 +1,8 @@
...
+  skip_before_action :authenticate_from_token!, only: [:index]
+  def index
+    render json:
+      CropsTagIndex.where(id: /#{Regexp.escape(params[:query].to_s)}/i)
+                         .pluck(:id)
```
Comment (simonv3) [inline app/controllers/api/v1/tags_controller.rb]: Fix these :)

File: app/models/crops_tag_index.rb [hunk 25]
```diff
@@ -0,0 +1,6 @@
+class CropsTagIndex
+  include Mongoid::Document
+  store_in collection: "crops_tags_index"
```
Comment (simonv3) [inline app/models/crops_tag_index.rb]: Fix this :)

File: spec/controllers/api/api_crops_controller_spec.rb [hunk 26]
```diff
@@ -48,10 +48,23 @@
...
     expect(crop.description).to eq('Updated')
+    expect(crop.tags).to eq('tag')
+  end
+
+  it 'tests whether tags get added as an array', js: true do
+    crop = FactoryGirl.create(:crop)
+    sign_in user
+    put :update,
+        id: crop.id,
+        data: { attributes: { tags_array: ['just', 'some', 'tags'] } }
```
Comment (simonv3) [inline spec/controllers/api/api_crops_controller_spec.rb]: "eh"

**Comment by simonv3** [comment]
(I didn't leave a comment everywhere because a lot of them are the same. I think find & replace is your friend here).

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss (hunk 8 above)
Comment (TanSA05) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: `_variables.scss` is the only file they're defined in, right? I had to define a variable for this one since I couldn't find it (find and replace) in that one.

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss (hunk 13 above)
Comment (TanSA05) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: $dark-gray is defined as #666666 :/

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss (hunk 14 above)
Comment (TanSA05) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: @simonv3 I did do these ones! Refer commit: [Nested Elements](https://github.com/openfarmcc/OpenFarm/pull/829/commits/cbd799e8e5aeb68868ace016f97027709fd7c525)
Is Hound not updating?

File: app/controllers/api/v1/tags_controller.rb (hunk 24 above)
Comment (TanSA05) [inline app/controllers/api/v1/tags_controller.rb]: I did already! Refer my branch: [tansa05issue676_2](https://github.com/TanSA05/OpenFarm/blob/tansa05issue676_2/app/controllers/api/v1/tags_controller.rb)
What am I doing wrong? :/

**Comment by TanSA05** [comment]
Thanks for taking out the time to comment on each warning, @simonv3! I'll try and fix all of them :simple_smile:

File: spec/controllers/api/api_crops_controller_spec.rb (hunk 26 above)
Comment (TanSA05) [inline spec/controllers/api/api_crops_controller_spec.rb]: Did this one already.

File: app/models/crops_tag_index.rb (hunk 25 above)
Comment (TanSA05) [inline app/models/crops_tag_index.rb]: Done already

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 27]
```diff
@@ -0,0 +1,391 @@
...
+        border: none;
+        background: none;
+        cursor: pointer;
+        vertical-align: middle;
+        font-weight: bold;
+        font-size: 16px;
+        color: $dark-gray;
+      }
+
+      .remove-button:active {
```
Comment (TanSA05) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: @simonv3 I'm not sure of how I should place the `.remove-button:active` part

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 28]
```diff
@@ -0,0 +1,391 @@
...
+          }
+        }
+
+        .input {
+
+          .input-group-sm {
+
+            .keywords {
+
+              .tags {
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: I can see why hound is complaining about this, it is a lot of nesting. Can you think of a way of refactoring this so that it's not so deep? Maybe you don't need to every layer? 

Eg. `.tag-item .tags { }` might be enough?

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss (hunk 27 above)
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: @TanSA05 how many `.remove-button`s are there? Is there just one `.remove-button` in the code? Then we don't need to nest it inside of `.tags` or `.tag-item`. 

If there's just one `.remove-button` in `.tags`. then we just need to nest it inside of `.tags`.

**Comment by simonv3** [comment]
(Sorry Hound doesn't seem to like you!)

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss [hunk 29]
```diff
@@ -0,0 +1,274 @@
...
+      background: none;
+      cursor: pointer;
+      vertical-align: middle;
+      font-weight: bold;
+      font-size: 16px;
+      color: $dark-gray;
+
+      &:active {
+        color: $of-red;
+      }
```
Comment (simonv3) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: I think you're missing a closing bracket here.

**Comment by simonv3** [comment]
@TanSA05 I think you're missing a closing bracket, and that should fix all of those failures!

File: app/assets/stylesheets/styles/components/crops/components/tags-input.scss (hunk 29 above)
Comment (TanSA05) [inline app/assets/stylesheets/styles/components/crops/components/tags-input.scss]: Yeah, fixed it! Thanks, @simonv3!

**Comment by simonv3** [comment]
Did some small fixes that hound complained about above, and merged!

**Comment by TanSA05** [comment]
Oh! Okay. I was working on them (hehe). Thanks! @simonv3
