### PR TITLE
Fix issue#837: Fixing Wonky Footer

### LINKED ISSUE #837: Footer links a little wonky
The saga continues...
capture

### PR DESCRIPTION
**Pull request by TanSA05**
The following is what the Modified Footer looks like.
* Used `flex` to divide the categories into columns
* Added icons to the links
* The Category Headings are the same as `crop-name`. I'm not very good with design but I hope this is alright.

Modified Footer

This fixes #837

### CODE REVIEW

File: config/initializers/secret_token.rb [hunk 1]
```diff
@@ -1 +1 @@
-OpenFarm::Application.config.secret_key_base = ENV['SECRET_KEY_BASE']
+OpenFarm::Application.config.secret_key_base = '4515c033ab231c7980dadd96ca279fdd2991d40737a91ffa2c6e706dc0337da4b46f261e259a9d4b603fa4d260bccd391859c4fd6aef4aa79b087650fbdbf027'
```
Comment (simonv3) [inline config/initializers/secret_token.rb]: Change this back please!

**Comment by simonv3** [comment]
Hey @TanSA05 that looks great (seriously pro :O). It looks like you need to rebase your PR though, you're including a bunch of commits from people who aren't you ;). Let me know if you need a hand with that.

**Comment by TanSA05** [comment]
Hey, @simonv3!
Thanks, you're sweet. It's mediocre at best :P
And, yes. I'll try to rebase. I was actually trying to rebase and it resulted in something else entirely. And I'll also change the `ENV` variable
