### PR TITLE
Switch image uploading to a library

### LINKED ISSUE #797: Enable image uploading on local machines
> Implement a new API action that allows POSTing to the server?
> Keep in mind that although that action would work in dev, it would probably not work on Heroku because of the 30 second time limit (for large files). implement a conditional that under the right conditions POSTs to the local server instead of AWS
> will require a new controller action. Maybe just dump the file into a URL in the /public directory. 
> /public/delete_this_stuff so people know its dev env junk and not part of the project
> make sure you .gitignore that folder, too

cc @RickCarlino

### PR DESCRIPTION
**Pull request by simonv3**
So that we don't have to maintain our own library for this.

I used `ng-file-upload` to upload to s3, essentially just taking out the existing ngs3upload library, which was pretty messy, and removing the uploader.js coffee script file which was just causing confusion. 

The result is slightly more straightforward, and it should be easier to now set up an alternative upload process for local development without s3 (because `ng-file-upload` can also handle this). 

Also removed angular-sanitize and angular libraries stored in our source code which closes #906.

Enabled image uploading on local machines. TODO: actually just realized I should check that the AWS stuff still works. Close #797.

Do a small fix to CSS querying.

### CODE REVIEW

File: config/application.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ class Application < Rails::Application
     config.middleware.insert_before 'ActionDispatch::Static', 'Rack::Cors' do
       allow do
         origins '*'
-        resource '/api/*',
+        resource '/api/v1/*',
```
Comment (simonv3) [inline config/application.rb]: This is so that we don't blanket allow CORS on our aws_controller.
